name: Build Libraries

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: 
    - master
    - dev
    - v*
    paths:
    - "src/**"
    - "build/**"
    - ".github/workflows/**"

env:
  NugetApiKey: ${{secrets.NUGETAPIKEY}}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet run --project build/ShinyApiBuild.csproj

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5