name: Build Libraries

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: 
    - master
    - dev
    - v*
    paths:
    - "src/**"
    - "build/**"
    - ".github/workflows/**"

env:
  NugetApiKey: ${{secrets.NUGETAPIKEY}}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Add .NET Workloads
      run: dotnet workload install maui

    - name: Build
      run: dotnet build apiservices.sln /restore -m -property:Configuration=Release -property:PublicRelease=true

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'

    - name: Publish NuGets
      if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate